version: '3.8'

services:
  # backend:
  #   image: messenger-api
  #   environment:
  #     TYPEORM_HOST: postgres-db
  #     TYPEORM_PORT: 5432
  #     CORS_WHITELIST: "https://app.messenger-db.com,http://localhost,http://localhost:4200,https://localhost:4200,https://localhost:80"
  #     TYPEORM_USERNAME: postgres
  #     TYPEORM_PASSWORD: postgres
  #     TYPEORM_DATABASE: messenger
  #     AUTH0_DOMAIN: dev-srcqo1kcftexp32u.uk.auth0.com
  #     AUTH0_ISS: dev-srcqo1kcftexp32u.uk.auth0.com
  #     AUTH0_CLIENT_ID: JtA1B5YM0gQun4ffFUfdCWunpm80fObeeQO
  #     AUTH0_CLIENT_SECRET: rZGdfXJJPy-SHGbMxMTChki8lWdJvR6ol7IEyxszbEyPbTJZYD_Qvl1DNlyfTMqr
  #     MAIN_UI_BASE_URL: http://localhost:3000
  #     SOCKET_BASE_URL: http://localhost:3000
  #     MAIN_UI_AUTH0_CLIENT_ID: 6o7hZ9ceKlY6OzWvo3FHRUSNEdI1iMyk
  #     MAIN_UI_AUTH0_CLIENT_DOMAIN: dev-srcqo1kcftexp32u.uk.auth0.com

  #   volumes:
  #     - 'messenger-datavolume:/app'
  #   ports:
      # - 3000:3000
      
  postgres-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: messenger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - messenger-datavolume:/var/lib/postgresql/data  
    ports:
      - "5432:5432"

volumes:
  messenger-datavolume:
