version: '3.8'

services:
  backend:
    image: messenger-api
    environment:
      TYPEORM_HOST: ${TYPEORM_HOST}
      TYPEORM_PORT: ${TYPEORM_PORT}
      CORS_WHITELIST: ${CORS_WHITELIST}
      TYPEORM_USERNAME: ${TYPEORM_USERNAME}
      TYPEORM_PASSWORD: ${TYPEORM_PASSWORD}
      TYPEORM_DATABASE: ${TYPEORM_DATABASE}
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_ISS: ${AUTH0_ISS}
      AUTH0_CLIENT_ID: ${AUTH0_CLIENT_ID}
      AUTH0_CLIENT_SECRET: ${AUTH0_CLIENT_SECRET}
      MAIN_UI_BASE_URL: ${MAIN_UI_BASE_URL}
      SOCKET_BASE_URL: ${SOCKET_BASE_URL}
      MAIN_UI_AUTH0_CLIENT_ID: ${MAIN_UI_AUTH0_CLIENT_ID}
      MAIN_UI_AUTH0_CLIENT_DOMAIN: ${MAIN_UI_AUTH0_CLIENT_DOMAIN}

    volumes:
      - 'messenger-datavolume:/app'
    ports:
      - 3000:3000
      
  postgres-db:
    image: postgres
    environment:
      POSTGRES_DB: messenger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - messenger-datavolume:/var/lib/postgresql/data  
    ports:
      - "5432:5432"

volumes:
  messenger-datavolume:
