version: '3.8'

services:
  backend:
    image: messenger-api
    # Use doppler secrets as environment variables
    environment:
      - DOPPLER_TOKEN
    # Run the service through doppler
    command: doppler run -- node /app/main.js  # Adjust this command based on your actual start command
    volumes:
      - 'messenger-datavolume:/app'
    ports:
      - 3000:3000
      
  postgres-db:
    image: postgres:13
    restart: always
    # For postgres, we'll inject the environment variables directly from doppler
    environment:
      - DOPPLER_TOKEN
    command: doppler run -- docker-entrypoint.sh postgres
    volumes:
      - messenger-datavolume:/var/lib/postgresql/data  
    ports:
      - "5432:5432"

volumes:
  messenger-datavolume: